SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

# Difficulty settings
DIFFICULTY_EASY = {
    "ASTEROID_SPAWN_RATE": 1.2,
    "ASTEROID_SPEED": 100,
    "ASTEROID_COUNT": 4,
    "NAME": "EASY"
}

DIFFICULTY_MEDIUM = {
    "ASTEROID_SPAWN_RATE": 0.8,
    "ASTEROID_SPEED": 150,
    "ASTEROID_COUNT": 6,
    "NAME": "MEDIUM"
}

DIFFICULTY_HARD = {
    "ASTEROID_SPAWN_RATE": 0.5,
    "ASTEROID_SPEED": 200,
    "ASTEROID_COUNT": 8,
    "NAME": "HARD"
}

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN = 0.3 

SHOT_RADIUS = 5

SCORE_LARGE_ASTEROID = 20
SCORE_MEDIUM_ASTEROID = 50
SCORE_SMALL_ASTEROID = 100

PLAYER_STARTING_LIVES = 3
PLAYER_RESPAWN_TIME = 2.0

PLAYER_ACCELERATION = 400
PLAYER_FRICTION = 0.9